name: Update gist with WakaTime stats
on:
  push:
    branches: master
  # see https://www.jianshu.com/p/c6f0f37fde31
  schedule:
    - cron: "0/30 */1 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 623eba84ef1152dac8a924cd4ede4855
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
